//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PurchaseOrderEmail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchaseOrderEmail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECommerce.Resources.PurchaseOrderEmail", typeof(PurchaseOrderEmail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr style=&quot;line-height:80px;&quot;&gt;
        ///	&lt;td&gt;{0}&lt;/td&gt;
        ///	&lt;td&gt;{1}&lt;/td&gt;
        ///	&lt;td&gt;{2}&lt;/td&gt;
        ///	&lt;td&gt;{3}&lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string ProductRow {
            get {
                return ResourceManager.GetString("ProductRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=windows-1252&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family:Arial; font-size:14px; text-align:center;&quot;&gt;
        ///	&lt;p&gt;Se ha generado una nueva orden de compra de &amp;copy;ForzaUltra, a continuación se presenta la información de la misma&lt;/p&gt;
        ///    &lt;div id=&quot;divWrapper&quot; style=&quot;width:500px; 
        ///                    border:1px solid silver;
        ///                    display: block;
        ///                    margin-left: auto;
        ///                    margi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PurchaseOrderEmailBodyForAdmin {
            get {
                return ResourceManager.GetString("PurchaseOrderEmailBodyForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=windows-1252&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family:Arial; font-size:14px; text-align:center;&quot;&gt;
        ///    &lt;div id=&quot;divWrapper&quot; style=&quot;width:500px; 
        ///                    border:1px solid silver;
        ///                    display: block;
        ///                    margin-left: auto;
        ///                    margin-right: auto;&quot;&gt;
        ///        &lt;div style=&quot;text-align:center; 
        ///                        background-color: black; 
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PurchaseOrderEmailBodyForCustomer {
            get {
                return ResourceManager.GetString("PurchaseOrderEmailBodyForCustomer", resourceCulture);
            }
        }
    }
}
